apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    app: kibana-logging
spec:
  type: NodePort  
  ports:
  - port: 5601
    nodePort: 31995
  selector:
    app: kibana-logging

