apiVersion: v1
kind: Service
metadata:
  name: svc-node-server
  labels:
    app: svc-node-server
  namespace: default
spec:
  type: NodePort 
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 31456
    protocol: TCP
    name: http
  selector:
    app: node-server
