apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-serverpy
  labels:
    app: docker-serverpy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-serverpy
  template:
    metadata:
      labels:
        app: docker-serverpy
    spec:
      containers:
      - name: docker-serverpy
        image: lucassales/docker-serverpy
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-serverpy
spec:
  selector:
    app: docker-serverpy
  ports:
    - protocol: TCP
      targetPort: 5000
  type: NodePort